# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.2.0

EAPI=7

CRATES="
adler32-1.0.4
ansi_term-0.11.0
ansi_term-0.12.1
anyhow-1.0.26
atty-0.2.14
bincode-1.2.1
bitflags-1.2.1
byteorder-1.3.2
c2-chacha-0.2.3
cfg-if-0.1.10
clap-2.33.0
codespan-0.7.0
codespan-reporting-0.7.0
crc32fast-1.2.0
crulz-0.0.3
delegate-0.3.0
either-1.5.3
flate2-1.0.13
getrandom-0.1.14
hermit-abi-0.1.6
itertools-0.8.2
lazy_static-1.4.0
libc-0.2.66
memmap-0.7.0
miniz_oxide-0.3.5
new_debug_unreachable-1.0.4
phf-0.8.0
phf_generator-0.8.0
phf_macros-0.8.0
phf_shared-0.8.0
ppv-lite86-0.2.6
precomputed-hash-0.1.1
proc-macro-hack-0.5.11
proc-macro2-0.4.30
proc-macro2-1.0.7
quote-0.6.13
quote-1.0.2
rand-0.7.3
rand_chacha-0.2.1
rand_core-0.5.1
rand_hc-0.2.0
rand_pcg-0.2.1
readfilez-0.2.0
serde-1.0.104
serde_derive-1.0.104
siphasher-0.3.1
string_cache-0.8.0
string_cache_codegen-0.5.1
strsim-0.8.0
syn-0.15.44
syn-1.0.13
termcolor-1.1.0
textwrap-0.11.0
unicode-segmentation-1.6.0
unicode-width-0.1.7
unicode-xid-0.1.0
unicode-xid-0.2.0
vec_map-0.8.1
wasi-0.9.0+wasi-snapshot-preview1
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.3
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="a rust implementation of the 'crulz' macro language interpreter"
HOMEPAGE="https://github.com/zserik/crulz-rs"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="amd64 ~arm x86"
IUSE="compile"

DEPEND=">=virtual/rust-1.40.0"
RDEPEND=""

src_compile() {
	cargo_src_compile \
		--no-default-features \
		$(usex compile "--features compile" "")
}

src_install() {
	cargo_src_install \
		--no-default-features \
		$(usex compile "--features compile" "")
}
